import { Vazirmatn } from 'next/font/google';
import type { Metadata } from 'next';
import { Providers } from './providers';
import { Header } from '@/core/layout/Header';
import './globals.css';

const vazir = Vazirmatn({
  subsets: ['arabic'],
  variable: '--font-vazir',
});

export const metadata: Metadata = {
  title: 'Telewebion | تلوبیون',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.variable} flex flex-col bg-background`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
